name: movies
publish_to: "none"
environment:
  sdk: ">=3.3.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  tmdb_api: ^2.2.3
  provider: ^6.0.0
  cached_network_image: ^3.2.3
  shimmer: ^3.0.0
  dartz: ^0.10.1
  http: ^1.2.0
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0